### ISSUE TITLE
使用过程中的部分问题和补充

### ISSUE THREAD

**Issue by Pull256** [cuglife/CUG_Safety_Lessons#1]
1、微信开启调试的详细教程见 https://blog.csdn.net/Jioho_chen/article/details/90636641
手机务必开启adb调试，并且需要先执行adb devices，在手机上点击允许usb调试后才可以
2、考试函数在后面几道题不会返回答案，不知道是什么原因（忘记截屏了）。但是最后几个题靠自己也没问题
3、刷课不敢尝试，担心进度溢出被发现

**Comment by Pull256** [comment]
### 课程ID
国家安全10(a1)
69,73,72,16,74,174,173,57,71,70
法律法规10(a2)
170,144,147,212,207,185,186,145,146,196
电信诈骗29(a3)
164,208,79,139,138,59,119,210,80,81,124,62,44,187,166,83,150,112,45,117,46,114,120,178,184,200,197,198,199
人身财产安全12(a4)
42,35,189,211,32,151,34,41,37,126,39,68
消防安全16(a5)
204,205,2,209,192,10,191,190,15,152,7,135,3,136,183,132
交通安全10(a6)
165,177,131,129,88,130,90,89,153,22
网信安全9(a7)
182,181,30,180,137,179,29,94,188
心理健康安全9(a8)
201,202,203,167,168,169,157,28,156
疫情防控安全7(a9)
25,158,23,102,154,175,155

### 代码
let a1= [69,73,72,16,74,174,173,57,71,70]
let a2= [170,144,147,212,207,185,186,145,146,196]
let a3= [164,208,79,139,138,59,119,210,80,81,124,62,44,187,166,83,150,112,45,117,46,114,120,178,184,200,197,198,199]
let a4= [42,35,189,211,32,151,34,41,37,126,39,68]
let a5= [204,205,2,209,192,10,191,190,15,152,7,135,3,136,183,132]
let a6= [165,177,131,129,88,130,90,89,153,22]
let a7= [182,181,30,180,137,179,29,94,188]
let a8= [201,202,203,167,168,169,157,28,156]
let a9= [25,158,23,102,154,175,155]
let aall=[69,73,72,16,74,174,173,57,71,70,170,144,147,212,207,185,186,145,146,196,164,208,79,139,138,59,119,210,80,81,124,62,44,187,166,83,150,112,45,117,46,114,120,178,184,200,197,198,199,42,35,189,211,32,151,34,41,37,126,39,68,204,205,2,209,192,10,191,190,15,152,7,135,3,136,183,132,165,177,131,129,88,130,90,89,153,22,182,181,30,180,137,179,29,94,188,201,202,203,167,168,169,157,28,156,25,158,23,102,154,175,155]

//a1到a9代表9个章节，由于部分章节已经学习过了，所以用这种半手动的方式控制学习的章节,学习所有章节就是aall
a=a9


//休眠函数，参考https://blog.csdn.net/weixin_41297324/article/details/111227398
function sleep(n) {
        var start = new Date().getTime();
        //  console.log('休眠前：' + start);
        while (true) {
            if (new Date().getTime() - start > n) {
                break;
            }
        }
        // console.log('休眠后：' + new Date().getTime());
    }
 
//主函数
function finished_course(course_id) {
    $.ajax({
        url: "http://study.weusstore.com/index/course/finished?cid=" + course_id,
        type: "GET",
        timeout: 5000,
        success: function (data) {
            console.log(data);
            console.log(course_id + " 完成学习！");
        },
        error: function (XMLHttpRequest, textStatus, errorThrown) {
        }
    });
}

//循环
for (var i = 0;i<a.length;i++){
finished_course(a[i]);
console.log(a[i]);
//间隔时间，单位毫秒
sleep(1000);
}

**Comment by Pull256** [comment]
注意：我人工校验了课程ID和代码，是没有问题的，但是在实际操作中，出现了进度大于100%的问题（但大的不多），目前找不到原因，请大家慎重使用。
可能是某一节课程重复学习了，或者是别的问题。

**仅供学习使用，后果自负**
（不好意思在issue上说了这么多，本来应该是merge一个上去的，但比较担心误导别人，就放在这里了）

**Comment by oaeen** [comment]
感谢补充，已更新
